// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartWaste.Infrastructure.Persistence;

#nullable disable

namespace SmartWaste.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922065633_AddWasteBinCaseInsensitiveIndex")]
    partial class AddWasteBinCaseInsensitiveIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.BinObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("FillLevelPercent")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WasteBinId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("WasteBinId", "RecordedAt")
                        .IsDescending(false, true);

                    b.ToTable("BinObservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_BinObservations_Condition", "\"Condition\" IN ('Good', 'Damaged', 'Blocked', 'Missing')");

                            t.HasCheckConstraint("CK_BinObservations_FillLevelPercent", "\"FillLevelPercent\" IN (0, 25, 50, 75, 100)");
                        });
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CollectionReason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreationMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Manual");

                    b.Property<string>("HandlingNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("RoutineDueDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchedulingReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Scheduled");

                    b.Property<string>("TaskCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TriggerObservationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WasteBinId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WasteReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TaskCode")
                        .IsUnique();

                    b.HasIndex("TriggerObservationId");

                    b.HasIndex("WasteBinId")
                        .IsUnique()
                        .HasDatabaseName("IX_CollectionTasks_WasteBinId_Active")
                        .HasFilter("\"WasteBinId\" IS NOT NULL AND \"Status\" IN ('Scheduled', 'Assigned', 'InProgress')");

                    b.HasIndex("WasteReportId")
                        .IsUnique()
                        .HasDatabaseName("IX_CollectionTasks_WasteReportId_Active")
                        .HasFilter("\"WasteReportId\" IS NOT NULL AND \"Status\" IN ('Scheduled', 'Assigned', 'InProgress')");

                    b.HasIndex("Status", "ScheduledAt");

                    b.ToTable("CollectionTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_CollectionTasks_OfficerDiscretion_Reason", "(\"CollectionReason\" != 'OfficerDiscretion') OR (\"SchedulingReason\" IS NOT NULL AND LENGTH(TRIM(\"SchedulingReason\")) > 0)");

                            t.HasCheckConstraint("CK_CollectionTasks_Reason_Consistency", "(\"WasteReportId\" IS NOT NULL AND \"CollectionReason\" = 'VerifiedReport') OR (\"WasteBinId\" IS NOT NULL AND \"CollectionReason\" IN ('FullOrBlockedBin', 'RoutineCollection', 'OfficerDiscretion'))");

                            t.HasCheckConstraint("CK_CollectionTasks_Status", "\"Status\" IN ('Scheduled', 'Assigned', 'InProgress', 'Completed', 'Failed', 'Cancelled')");

                            t.HasCheckConstraint("CK_CollectionTasks_Target_XOR", "(\"WasteReportId\" IS NOT NULL AND \"WasteBinId\" IS NULL) OR (\"WasteReportId\" IS NULL AND \"WasteBinId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionTaskScheduleHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NewScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PreviousScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RescheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RescheduledByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RescheduledByUserId");

                    b.HasIndex("CollectionTaskId", "RescheduledAt");

                    b.ToTable("CollectionTaskScheduleHistories", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionTaskStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("CollectionTaskId", "ChangedAt");

                    b.ToTable("CollectionTaskStatusHistories", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.WasteBin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AdministrativeStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.Property<string>("BinCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CapacityLiters")
                        .HasColumnType("integer");

                    b.Property<int[]>("CollectionWeekdays")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastCollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdministrativeStatus");

                    b.HasIndex("BinCode")
                        .IsUnique();

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("WasteBins", null, t =>
                        {
                            t.HasCheckConstraint("CK_WasteBins_AdministrativeStatus", "\"AdministrativeStatus\" IN ('Active', 'OutOfService', 'Retired')");

                            t.HasCheckConstraint("CK_WasteBins_CapacityLiters", "\"CapacityLiters\" > 0");

                            t.HasCheckConstraint("CK_WasteBins_CollectionWeekdays_Range", "\"CollectionWeekdays\" <@ ARRAY[1, 2, 3, 4, 5, 6, 7]");

                            t.HasCheckConstraint("CK_WasteBins_Coordinates", "\"Latitude\" >= -90.0 AND \"Latitude\" <= 90.0 AND \"Longitude\" >= -180.0 AND \"Longitude\" <= 180.0");
                        });
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.WasteBinAcceptedWasteType", b =>
                {
                    b.Property<Guid>("WasteBinId")
                        .HasColumnType("uuid");

                    b.Property<string>("WasteType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("WasteBinId", "WasteType");

                    b.ToTable("WasteBinAcceptedWasteTypes", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Reporting.Entities.ReportAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("WasteReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WasteReportId");

                    b.ToTable("ReportAttachments", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Reporting.Entities.WasteReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Priority")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WasteType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("VerifiedByUserId");

                    b.HasIndex("Status", "WasteType");

                    b.ToTable("WasteReports", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Reporting.Entities.WasteReportStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("WasteReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("WasteReportId");

                    b.ToTable("WasteReportStatusHistories", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.BinObservation", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Collection.Entities.WasteBin", "WasteBin")
                        .WithMany("Observations")
                        .HasForeignKey("WasteBinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordedByUser");

                    b.Navigation("WasteBin");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionTask", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Collection.Entities.BinObservation", "TriggerObservation")
                        .WithMany()
                        .HasForeignKey("TriggerObservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartWaste.Domain.Collection.Entities.WasteBin", "WasteBin")
                        .WithMany("CollectionTasks")
                        .HasForeignKey("WasteBinId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartWaste.Domain.Reporting.Entities.WasteReport", "WasteReport")
                        .WithMany()
                        .HasForeignKey("WasteReportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("TriggerObservation");

                    b.Navigation("WasteBin");

                    b.Navigation("WasteReport");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionTaskScheduleHistory", b =>
                {
                    b.HasOne("SmartWaste.Domain.Collection.Entities.CollectionTask", "CollectionTask")
                        .WithMany("ScheduleHistory")
                        .HasForeignKey("CollectionTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "RescheduledByUser")
                        .WithMany()
                        .HasForeignKey("RescheduledByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionTask");

                    b.Navigation("RescheduledByUser");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionTaskStatusHistory", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartWaste.Domain.Collection.Entities.CollectionTask", "CollectionTask")
                        .WithMany("StatusHistory")
                        .HasForeignKey("CollectionTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("CollectionTask");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.WasteBinAcceptedWasteType", b =>
                {
                    b.HasOne("SmartWaste.Domain.Collection.Entities.WasteBin", "WasteBin")
                        .WithMany("AcceptedWasteTypes")
                        .HasForeignKey("WasteBinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WasteBin");
                });

            modelBuilder.Entity("SmartWaste.Domain.Reporting.Entities.ReportAttachment", b =>
                {
                    b.HasOne("SmartWaste.Domain.Reporting.Entities.WasteReport", "WasteReport")
                        .WithMany("Attachments")
                        .HasForeignKey("WasteReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WasteReport");
                });

            modelBuilder.Entity("SmartWaste.Domain.Reporting.Entities.WasteReport", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Citizen");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("SmartWaste.Domain.Reporting.Entities.WasteReportStatusHistory", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartWaste.Domain.Reporting.Entities.WasteReport", "WasteReport")
                        .WithMany("StatusHistory")
                        .HasForeignKey("WasteReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("WasteReport");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionTask", b =>
                {
                    b.Navigation("ScheduleHistory");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.WasteBin", b =>
                {
                    b.Navigation("AcceptedWasteTypes");

                    b.Navigation("CollectionTasks");

                    b.Navigation("Observations");
                });

            modelBuilder.Entity("SmartWaste.Domain.Reporting.Entities.WasteReport", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
