// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartWaste.Infrastructure.Persistence;

#nullable disable

namespace SmartWaste.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("CollectionAssignmentNumberSequence");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.BinObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("FillLevelPercent")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WasteBinId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("WasteBinId", "RecordedAt")
                        .IsDescending(false, true);

                    b.ToTable("BinObservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_BinObservations_Condition", "\"Condition\" IN ('Good', 'Damaged', 'Blocked', 'Missing')");

                            t.HasCheckConstraint("CK_BinObservations_FillLevelPercent", "\"FillLevelPercent\" IN (0, 25, 50, 75, 100)");
                        });
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("AssignmentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"CollectionAssignmentNumberSequence\"'::regclass)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompatibilityAcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompatibilityAcknowledgedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompatibilityAcknowledgement")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Assigned");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("AssignmentNumber")
                        .IsUnique();

                    b.HasIndex("CompatibilityAcknowledgedByUserId");

                    b.HasIndex("DriverId")
                        .IsUnique()
                        .HasDatabaseName("IX_CollectionAssignments_DriverId_Unfinished")
                        .HasFilter("\"Status\" IN ('Assigned', 'InProgress')");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("IX_CollectionAssignments_VehicleId_Unfinished")
                        .HasFilter("\"Status\" IN ('Assigned', 'InProgress')");

                    b.ToTable("CollectionAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_CollectionAssignments_AssignmentNumber", "\"AssignmentNumber\" > 0");

                            t.HasCheckConstraint("CK_CollectionAssignments_CancellationReason", "(\"Status\" <> 'Cancelled') OR (\"CancellationReason\" IS NOT NULL AND LENGTH(TRIM(\"CancellationReason\")) BETWEEN 5 AND 500)");

                            t.HasCheckConstraint("CK_CollectionAssignments_Status", "\"Status\" IN ('Assigned', 'InProgress', 'Completed', 'PartiallyCompleted', 'Failed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionAssignmentStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("CollectionAssignmentId", "ChangedAt");

                    b.ToTable("CollectionAssignmentStatusHistories", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionAssignmentTaskClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CollectionAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionTaskId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ReleaseReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReleasedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CollectionTaskId")
                        .IsUnique()
                        .HasDatabaseName("IX_CollectionAssignmentTaskClaims_TaskId_Active")
                        .HasFilter("\"IsActive\" = TRUE");

                    b.HasIndex("ReleasedByUserId");

                    b.HasIndex("CollectionAssignmentId", "CollectionTaskId")
                        .IsUnique();

                    b.ToTable("CollectionAssignmentTaskClaims", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CollectionReason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreationMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Manual");

                    b.Property<string>("HandlingNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("RoutineDueDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchedulingReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Scheduled");

                    b.Property<string>("TaskCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TriggerObservationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WasteBinId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WasteReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TaskCode")
                        .IsUnique();

                    b.HasIndex("TriggerObservationId");

                    b.HasIndex("WasteBinId")
                        .IsUnique()
                        .HasDatabaseName("IX_CollectionTasks_WasteBinId_Active")
                        .HasFilter("\"WasteBinId\" IS NOT NULL AND \"Status\" IN ('Scheduled', 'Assigned', 'InProgress')");

                    b.HasIndex("WasteReportId")
                        .IsUnique()
                        .HasDatabaseName("IX_CollectionTasks_WasteReportId_Active")
                        .HasFilter("\"WasteReportId\" IS NOT NULL AND \"Status\" IN ('Scheduled', 'Assigned', 'InProgress')");

                    b.HasIndex("Status", "ScheduledAt");

                    b.ToTable("CollectionTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_CollectionTasks_OfficerDiscretion_Reason", "(\"CollectionReason\" != 'OfficerDiscretion') OR (\"SchedulingReason\" IS NOT NULL AND LENGTH(TRIM(\"SchedulingReason\")) > 0)");

                            t.HasCheckConstraint("CK_CollectionTasks_Reason_Consistency", "(\"WasteReportId\" IS NOT NULL AND \"CollectionReason\" = 'VerifiedReport') OR (\"WasteBinId\" IS NOT NULL AND \"CollectionReason\" IN ('FullOrBlockedBin', 'RoutineCollection', 'OfficerDiscretion'))");

                            t.HasCheckConstraint("CK_CollectionTasks_Status", "\"Status\" IN ('Scheduled', 'Assigned', 'InProgress', 'Completed', 'Failed', 'Cancelled')");

                            t.HasCheckConstraint("CK_CollectionTasks_Target_XOR", "(\"WasteReportId\" IS NOT NULL AND \"WasteBinId\" IS NULL) OR (\"WasteReportId\" IS NULL AND \"WasteBinId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionTaskScheduleHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NewScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PreviousScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RescheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RescheduledByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RescheduledByUserId");

                    b.HasIndex("CollectionTaskId", "RescheduledAt");

                    b.ToTable("CollectionTaskScheduleHistories", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionTaskStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("CollectionTaskId", "ChangedAt");

                    b.ToTable("CollectionTaskStatusHistories", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EstimatedDistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("EstimatedDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("RouteGeometry")
                        .HasColumnType("text");

                    b.Property<string>("RoutingMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("ManualOrder");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CollectionAssignmentId")
                        .IsUnique();

                    b.ToTable("Routes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Routes_RoutingMethod", "\"RoutingMethod\" IN ('ManualOrder', 'VerifiedProvider')");
                        });
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.RouteStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionAssignmentTaskClaimId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CollectionAssignmentTaskClaimId")
                        .IsUnique();

                    b.HasIndex("CollectionTaskId");

                    b.HasIndex("CollectionAssignmentTaskClaimId", "CollectionTaskId");

                    b.HasIndex("RouteId", "Sequence")
                        .IsUnique();

                    b.ToTable("RouteStops", null, t =>
                        {
                            t.HasCheckConstraint("CK_RouteStops_Failure", "(\"Status\" <> 'Failed' AND \"FailureReason\" IS NULL) OR (\"Status\" = 'Failed' AND \"FailureReason\" IS NOT NULL AND LENGTH(TRIM(\"FailureReason\")) BETWEEN 5 AND 500)");

                            t.HasCheckConstraint("CK_RouteStops_Sequence", "\"Sequence\" > 0");

                            t.HasCheckConstraint("CK_RouteStops_Status", "\"Status\" IN ('Pending', 'Completed', 'Failed')");
                        });
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.RouteStopStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RouteStopId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("RouteStopId", "ChangedAt");

                    b.ToTable("RouteStopStatusHistories", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CapacityLiters")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Available");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("Vehicles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vehicles_CapacityLiters", "\"CapacityLiters\" > 0");

                            t.HasCheckConstraint("CK_Vehicles_OperationalStatus", "\"OperationalStatus\" IN ('Available', 'Maintenance', 'Inactive')");

                            t.HasCheckConstraint("CK_Vehicles_VehicleType", "\"VehicleType\" IN ('Compactor', 'Flatbed', 'Tipper', 'SmallVan')");
                        });
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.VehicleSupportedWasteType", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<string>("WasteType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("VehicleId", "WasteType");

                    b.ToTable("VehicleSupportedWasteTypes", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.WasteBin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AdministrativeStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.Property<string>("BinCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CapacityLiters")
                        .HasColumnType("integer");

                    b.Property<int[]>("CollectionWeekdays")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastCollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdministrativeStatus");

                    b.HasIndex("BinCode")
                        .IsUnique();

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("WasteBins", null, t =>
                        {
                            t.HasCheckConstraint("CK_WasteBins_AdministrativeStatus", "\"AdministrativeStatus\" IN ('Active', 'OutOfService', 'Retired')");

                            t.HasCheckConstraint("CK_WasteBins_CapacityLiters", "\"CapacityLiters\" > 0");

                            t.HasCheckConstraint("CK_WasteBins_CollectionWeekdays_Range", "\"CollectionWeekdays\" <@ ARRAY[1, 2, 3, 4, 5, 6, 7]");

                            t.HasCheckConstraint("CK_WasteBins_Coordinates", "\"Latitude\" >= -90.0 AND \"Latitude\" <= 90.0 AND \"Longitude\" >= -180.0 AND \"Longitude\" <= 180.0");
                        });
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.WasteBinAcceptedWasteType", b =>
                {
                    b.Property<Guid>("WasteBinId")
                        .HasColumnType("uuid");

                    b.Property<string>("WasteType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("WasteBinId", "WasteType");

                    b.ToTable("WasteBinAcceptedWasteTypes", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Complaints.Entities.Complaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Submitted");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "Category");

                    b.ToTable("Complaints", null, t =>
                        {
                            t.HasCheckConstraint("CK_Complaints_Category", "\"Category\" IN ('MissedCollection', 'DelayedService', 'PoorService', 'UnresolvedIssue', 'Other')");

                            t.HasCheckConstraint("CK_Complaints_Coordinates", "(\"Latitude\" IS NULL AND \"Longitude\" IS NULL) OR (\"Latitude\" IS NOT NULL AND \"Longitude\" IS NOT NULL AND \"Latitude\" >= -90.0 AND \"Latitude\" <= 90.0 AND \"Longitude\" >= -180.0 AND \"Longitude\" <= 180.0)");

                            t.HasCheckConstraint("CK_Complaints_Status", "\"Status\" IN ('Submitted', 'InReview', 'Resolved')");
                        });
                });

            modelBuilder.Entity("SmartWaste.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Entities.DriverProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Available");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EligibilityNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsEligible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("DriverProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_DriverProfiles_AvailabilityStatus", "\"AvailabilityStatus\" IN ('Available', 'OffDuty')");
                        });
                });

            modelBuilder.Entity("SmartWaste.Domain.Operations.Entities.OperationalIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Reported");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DriverId");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "IssueType");

                    b.ToTable("OperationalIssues", null, t =>
                        {
                            t.HasCheckConstraint("CK_OperationalIssues_Coordinates", "(\"Latitude\" IS NULL AND \"Longitude\" IS NULL) OR (\"Latitude\" IS NOT NULL AND \"Longitude\" IS NOT NULL AND \"Latitude\" >= -90.0 AND \"Latitude\" <= 90.0 AND \"Longitude\" >= -180.0 AND \"Longitude\" <= 180.0)");

                            t.HasCheckConstraint("CK_OperationalIssues_Status", "\"Status\" IN ('Reported', 'InReview', 'Resolved')");

                            t.HasCheckConstraint("CK_OperationalIssues_Type", "\"IssueType\" IN ('VehicleProblem', 'RoadOrAccessIssue', 'EquipmentProblem', 'SafetyConcern', 'OperationalDelay', 'Other')");
                        });
                });

            modelBuilder.Entity("SmartWaste.Domain.Reporting.Entities.ReportAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("WasteReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WasteReportId");

                    b.ToTable("ReportAttachments", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Reporting.Entities.WasteReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Priority")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WasteType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("VerifiedByUserId");

                    b.HasIndex("Status", "WasteType");

                    b.ToTable("WasteReports", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Reporting.Entities.WasteReportStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("WasteReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("WasteReportId");

                    b.ToTable("WasteReportStatusHistories", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Workflow.Entities.AgentWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("None");

                    b.Property<string>("FinalOutcome")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ProcessingAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ProcessingLeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProcessingLeaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Created");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("ManualOperationalPlanning");

                    b.Property<Guid?>("TriggeringWasteReportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AgentWorkflows_CreatedAt");

                    b.HasIndex("InitiatedByUserId")
                        .HasDatabaseName("IX_AgentWorkflows_InitiatedByUserId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_AgentWorkflows_Status");

                    b.HasIndex("TriggerType")
                        .HasDatabaseName("IX_AgentWorkflows_TriggerType");

                    b.HasIndex("TriggeringWasteReportId")
                        .IsUnique()
                        .HasDatabaseName("IX_AgentWorkflows_TriggeringWasteReportId")
                        .HasFilter("\"TriggeringWasteReportId\" IS NOT NULL");

                    b.ToTable("AgentWorkflows", null, t =>
                        {
                            t.HasCheckConstraint("CK_AgentWorkflows_Objective", "LENGTH(TRIM(\"Objective\")) >= 5");

                            t.HasCheckConstraint("CK_AgentWorkflows_ProcessingAttemptCount", "\"ProcessingAttemptCount\" >= 0");

                            t.HasCheckConstraint("CK_AgentWorkflows_Status", "\"Status\" IN ('Created', 'Planning', 'AwaitingCollectionApproval', 'CollectionNeedsRevision', 'CollectionApproved', 'CreatingScheduledTasks', 'FleetPlanning', 'OperationalValidation', 'AwaitingDispatchApproval', 'DispatchNeedsRevision', 'DispatchApproved', 'ExecutingAssignments', 'Completed', 'Rejected', 'Failed', 'AwaitingReportVerification')");

                            t.HasCheckConstraint("CK_AgentWorkflows_TriggerReport", "(\"TriggerType\" = 'ManualOperationalPlanning' AND \"TriggeringWasteReportId\" IS NULL) OR (\"TriggerType\" = 'CitizenReportSubmission' AND \"TriggeringWasteReportId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SmartWaste.Domain.Workflow.Entities.AgentWorkflowApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DecisionPayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkflowStepId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_AgentWorkflowApprovals_WorkflowId");

                    b.HasIndex("WorkflowStepId");

                    b.ToTable("AgentWorkflowApprovals", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Workflow.Entities.AgentWorkflowExecutionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecutionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkflowStepId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_AgentWorkflowExecutionResults_WorkflowId");

                    b.HasIndex("WorkflowStepId");

                    b.ToTable("AgentWorkflowExecutionResults", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Domain.Workflow.Entities.AgentWorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("InputJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ValidationJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_AgentWorkflowSteps_WorkflowId_Sequence");

                    b.ToTable("AgentWorkflowSteps", null, t =>
                        {
                            t.HasCheckConstraint("CK_AgentWorkflowSteps_Sequence", "\"Sequence\" > 0");

                            t.HasCheckConstraint("CK_AgentWorkflowSteps_Status", "\"Status\" IN ('Pending', 'Running', 'Completed', 'Failed', 'Skipped')");
                        });
                });

            modelBuilder.Entity("SmartWaste.Domain.Workflow.Entities.AgentWorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("WorkflowId", "ChangedAt")
                        .HasDatabaseName("IX_AgentWorkflowTransitions_WorkflowId_ChangedAt");

                    b.ToTable("AgentWorkflowTransitions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.BinObservation", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Collection.Entities.WasteBin", "WasteBin")
                        .WithMany("Observations")
                        .HasForeignKey("WasteBinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordedByUser");

                    b.Navigation("WasteBin");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionAssignment", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "CompatibilityAcknowledgedByUser")
                        .WithMany()
                        .HasForeignKey("CompatibilityAcknowledgedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartWaste.Domain.Entities.DriverProfile", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Collection.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("CompatibilityAcknowledgedByUser");

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionAssignmentStatusHistory", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartWaste.Domain.Collection.Entities.CollectionAssignment", "CollectionAssignment")
                        .WithMany("StatusHistory")
                        .HasForeignKey("CollectionAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("CollectionAssignment");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionAssignmentTaskClaim", b =>
                {
                    b.HasOne("SmartWaste.Domain.Collection.Entities.CollectionAssignment", "CollectionAssignment")
                        .WithMany("TaskClaims")
                        .HasForeignKey("CollectionAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Collection.Entities.CollectionTask", "CollectionTask")
                        .WithMany()
                        .HasForeignKey("CollectionTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "ReleasedByUser")
                        .WithMany()
                        .HasForeignKey("ReleasedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CollectionAssignment");

                    b.Navigation("CollectionTask");

                    b.Navigation("ReleasedByUser");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionTask", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Collection.Entities.BinObservation", "TriggerObservation")
                        .WithMany()
                        .HasForeignKey("TriggerObservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartWaste.Domain.Collection.Entities.WasteBin", "WasteBin")
                        .WithMany("CollectionTasks")
                        .HasForeignKey("WasteBinId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartWaste.Domain.Reporting.Entities.WasteReport", "WasteReport")
                        .WithMany()
                        .HasForeignKey("WasteReportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("TriggerObservation");

                    b.Navigation("WasteBin");

                    b.Navigation("WasteReport");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionTaskScheduleHistory", b =>
                {
                    b.HasOne("SmartWaste.Domain.Collection.Entities.CollectionTask", "CollectionTask")
                        .WithMany("ScheduleHistory")
                        .HasForeignKey("CollectionTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "RescheduledByUser")
                        .WithMany()
                        .HasForeignKey("RescheduledByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionTask");

                    b.Navigation("RescheduledByUser");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionTaskStatusHistory", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartWaste.Domain.Collection.Entities.CollectionTask", "CollectionTask")
                        .WithMany("StatusHistory")
                        .HasForeignKey("CollectionTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("CollectionTask");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.Route", b =>
                {
                    b.HasOne("SmartWaste.Domain.Collection.Entities.CollectionAssignment", "CollectionAssignment")
                        .WithOne("Route")
                        .HasForeignKey("SmartWaste.Domain.Collection.Entities.Route", "CollectionAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionAssignment");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.RouteStop", b =>
                {
                    b.HasOne("SmartWaste.Domain.Collection.Entities.CollectionTask", "CollectionTask")
                        .WithMany()
                        .HasForeignKey("CollectionTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Collection.Entities.Route", "Route")
                        .WithMany("Stops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Collection.Entities.CollectionAssignmentTaskClaim", "CollectionAssignmentTaskClaim")
                        .WithMany()
                        .HasForeignKey("CollectionAssignmentTaskClaimId", "CollectionTaskId")
                        .HasPrincipalKey("Id", "CollectionTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionAssignmentTaskClaim");

                    b.Navigation("CollectionTask");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.RouteStopStatusHistory", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartWaste.Domain.Collection.Entities.RouteStop", "RouteStop")
                        .WithMany("StatusHistory")
                        .HasForeignKey("RouteStopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("RouteStop");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.VehicleSupportedWasteType", b =>
                {
                    b.HasOne("SmartWaste.Domain.Collection.Entities.Vehicle", "Vehicle")
                        .WithMany("SupportedWasteTypes")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.WasteBinAcceptedWasteType", b =>
                {
                    b.HasOne("SmartWaste.Domain.Collection.Entities.WasteBin", "WasteBin")
                        .WithMany("AcceptedWasteTypes")
                        .HasForeignKey("WasteBinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WasteBin");
                });

            modelBuilder.Entity("SmartWaste.Domain.Complaints.Entities.Complaint", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Citizen");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("SmartWaste.Domain.Entities.DriverProfile", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "User")
                        .WithOne("DriverProfile")
                        .HasForeignKey("SmartWaste.Domain.Entities.DriverProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartWaste.Domain.Operations.Entities.OperationalIssue", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Driver");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("SmartWaste.Domain.Reporting.Entities.ReportAttachment", b =>
                {
                    b.HasOne("SmartWaste.Domain.Reporting.Entities.WasteReport", "WasteReport")
                        .WithMany("Attachments")
                        .HasForeignKey("WasteReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WasteReport");
                });

            modelBuilder.Entity("SmartWaste.Domain.Reporting.Entities.WasteReport", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Citizen");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("SmartWaste.Domain.Reporting.Entities.WasteReportStatusHistory", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartWaste.Domain.Reporting.Entities.WasteReport", "WasteReport")
                        .WithMany("StatusHistory")
                        .HasForeignKey("WasteReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("WasteReport");
                });

            modelBuilder.Entity("SmartWaste.Domain.Workflow.Entities.AgentWorkflow", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "InitiatedByUser")
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Reporting.Entities.WasteReport", "TriggeringWasteReport")
                        .WithMany()
                        .HasForeignKey("TriggeringWasteReportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InitiatedByUser");

                    b.Navigation("TriggeringWasteReport");
                });

            modelBuilder.Entity("SmartWaste.Domain.Workflow.Entities.AgentWorkflowApproval", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "DecidedByUser")
                        .WithMany()
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Workflow.Entities.AgentWorkflow", "Workflow")
                        .WithMany("Approvals")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Workflow.Entities.AgentWorkflowStep", "WorkflowStep")
                        .WithMany()
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DecidedByUser");

                    b.Navigation("Workflow");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("SmartWaste.Domain.Workflow.Entities.AgentWorkflowExecutionResult", b =>
                {
                    b.HasOne("SmartWaste.Domain.Workflow.Entities.AgentWorkflow", "Workflow")
                        .WithMany("ExecutionResults")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartWaste.Domain.Workflow.Entities.AgentWorkflowStep", "WorkflowStep")
                        .WithMany()
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Workflow");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("SmartWaste.Domain.Workflow.Entities.AgentWorkflowStep", b =>
                {
                    b.HasOne("SmartWaste.Domain.Workflow.Entities.AgentWorkflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("SmartWaste.Domain.Workflow.Entities.AgentWorkflowTransition", b =>
                {
                    b.HasOne("SmartWaste.Domain.Entities.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartWaste.Domain.Workflow.Entities.AgentWorkflow", "Workflow")
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionAssignment", b =>
                {
                    b.Navigation("Route");

                    b.Navigation("StatusHistory");

                    b.Navigation("TaskClaims");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.CollectionTask", b =>
                {
                    b.Navigation("ScheduleHistory");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.Route", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.RouteStop", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.Vehicle", b =>
                {
                    b.Navigation("SupportedWasteTypes");
                });

            modelBuilder.Entity("SmartWaste.Domain.Collection.Entities.WasteBin", b =>
                {
                    b.Navigation("AcceptedWasteTypes");

                    b.Navigation("CollectionTasks");

                    b.Navigation("Observations");
                });

            modelBuilder.Entity("SmartWaste.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("DriverProfile");
                });

            modelBuilder.Entity("SmartWaste.Domain.Reporting.Entities.WasteReport", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("SmartWaste.Domain.Workflow.Entities.AgentWorkflow", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("ExecutionResults");

                    b.Navigation("Steps");

                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
