import React from 'react';
import { humanizeSourceMentions, needLabel } from '../../../utils/displayReferences';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../../components/ui/Card';
import type { NeedHandlingRecommendation, AgentWorkflowStep } from '../types/agentWorkflow';
import { formatWorkflowDate } from '../utils/workflowPresentation';
import { getCollectionPlanningOutput } from '../utils/workflowDetailPresentation';

const NeedRecommendationList: React.FC<{ title: string; items: NeedHandlingRecommendation[]; emptyText: string; binCodes?: Record<string, string> }> = ({ title, items, emptyText, binCodes }) => <section><h3 className="font-semibold text-slate-900">{title}</h3>{items.length === 0 ? <p className="mt-2 text-sm text-slate-500">{emptyText}</p> : <ul className="mt-2 space-y-2">{items.map((item) => <li key={`${item.needReference.needId}-${item.rationale}`} className="rounded-lg border border-slate-200 p-3 text-sm"><p className="font-semibold text-slate-800">{needLabel(item.needReference.targetType, item.needReference.needId, binCodes)} <span className="font-normal text-slate-500">· {item.needReference.urgency}</span></p>{item.proposedSchedule && <p className="mt-1 text-slate-600"><span className="font-semibold">Proposed schedule:</span> {formatWorkflowDate(item.proposedSchedule.scheduledAt)}</p>}<p className="mt-1 text-slate-600">{humanizeSourceMentions(item.rationale, binCodes)}</p></li>)}</ul>}</section>;

export const CollectionPlanningSection: React.FC<{ step: AgentWorkflowStep | null; binCodes?: Record<string, string> }> = ({ step, binCodes }) => {
  const output = getCollectionPlanningOutput(step);
  return <Card><CardHeader><CardTitle>Collection Planning</CardTitle><CardDescription>Proposed collection groups and schedules generated from authoritative collection needs.</CardDescription></CardHeader><CardContent>
    {output.kind === 'missing' && <p className="text-sm text-slate-500">Collection Planning result unavailable.</p>}
    {output.kind === 'invalid' && <p className="text-sm text-slate-500">Result unavailable or incompatible with the current format.</p>}
    {output.kind === 'value' && <div className="space-y-5">
      <div className="grid grid-cols-1 gap-3 text-sm sm:grid-cols-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Candidate groups</p><p className="mt-1 font-semibold text-slate-900">{output.value.candidateGroups.length}</p></div><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Separate handling</p><p className="mt-1 font-semibold text-slate-900">{output.value.separateHandling.length}</p></div><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Deferred needs</p><p className="mt-1 font-semibold text-slate-900">{output.value.deferredNeeds.length}</p></div></div>
      <div className={`rounded-lg border p-4 text-sm ${output.value.isCompleteSnapshot ? 'border-emerald-200 bg-emerald-50 text-emerald-900' : 'border-amber-200 bg-amber-50 text-amber-900'}`}><p className="font-semibold">{output.value.isCompleteSnapshot ? 'Complete source snapshot' : 'Partial source snapshot'}</p><p className="mt-1">Source: {output.value.sourceTotalCount} needs across {output.value.sourceTotalPages} pages; retrieved pages: {output.value.retrievedPages.join(', ') || '—'}.</p></div>
      {output.value.status === 'partial' && <p role="note" className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">This planning result used only part of the authoritative source snapshot.</p>}
      {output.value.status === 'empty' ? <p className="rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600">No collection needs were available for planning.</p> : <section><h3 className="font-semibold text-slate-900">Proposed collection groups</h3><ul className="mt-3 space-y-3">{output.value.candidateGroups.map((group) => <li key={group.groupId} className="rounded-lg border border-slate-200 p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h4 className="font-semibold text-slate-900">Group {group.groupId}</h4><p className="mt-1 text-sm text-slate-600">{humanizeSourceMentions(group.rationale, binCodes)}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">Proposed schedule: {formatWorkflowDate(group.proposedSchedule.scheduledAt)}</span></div><p className="mt-3 text-sm text-slate-600"><span className="font-semibold text-slate-700">Scheduling reason:</span> {humanizeSourceMentions(group.proposedSchedule.schedulingReason, binCodes)}</p><p className="mt-2 text-sm text-slate-600"><span className="font-semibold text-slate-700">Included needs:</span> {group.needReferences.map((reference) => `${needLabel(reference.targetType, reference.needId, binCodes)} (${reference.urgency})`).join(', ')}</p>{group.wasteHandlingConsiderations.length > 0 && <p className="mt-2 text-sm text-slate-600"><span className="font-semibold text-slate-700">Handling considerations:</span> {group.wasteHandlingConsiderations.map((item) => humanizeSourceMentions(item, binCodes)).join('; ')}</p>}{group.warnings.length > 0 && <p className="mt-2 text-sm text-amber-800"><span className="font-semibold">Warnings:</span> {group.warnings.map((item) => humanizeSourceMentions(item, binCodes)).join('; ')}</p>}</li>)}</ul></section>}
      <div className="grid gap-5 lg:grid-cols-2"><NeedRecommendationList title="Separate handling" items={output.value.separateHandling} emptyText="No separate handling recommendations." binCodes={binCodes} /><NeedRecommendationList title="Deferred needs" items={output.value.deferredNeeds} emptyText="No deferred needs." binCodes={binCodes} /></div>
      {output.value.warnings.length > 0 && <div role="note" className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><p className="font-semibold">Planning notices</p><ul className="mt-2 list-disc space-y-1 pl-5">{output.value.warnings.map((warning) => <li key={warning}>{humanizeSourceMentions(warning, binCodes)}</li>)}</ul></div>}
    </div>}
  </CardContent></Card>;
};
