using FluentValidation;
using Microsoft.EntityFrameworkCore;
using SmartWaste.Application.Collection.DTOs.Responses;
using SmartWaste.Application.Collection.Interfaces;
using SmartWaste.Application.Collection.Queries;
using SmartWaste.Application.Common.Exceptions;
using SmartWaste.Application.Common.Models;
using SmartWaste.Domain.Collection.Entities;
using SmartWaste.Domain.Collection.Enums;
using SmartWaste.Domain.Common;
using SmartWaste.Infrastructure.Persistence;

namespace SmartWaste.Infrastructure.Collection.Services;

public sealed class AssignmentReadService(AppDbContext db) : IAssignmentReadService
{
    public async Task<PagedResult<AssignmentTaskDto>> GetAvailableTasksAsync(AvailableAssignmentTaskQuery q, Guid actor, string role, CancellationToken ct=default) { RequireStaff(role); Validate(q.Page,q.PageSize); var source=db.CollectionTasks.AsNoTracking().Include(x=>x.WasteReport).Include(x=>x.WasteBin).Where(x=>x.Status==CollectionTaskStatus.Scheduled && !db.CollectionAssignmentTaskClaims.Any(c=>c.CollectionTaskId==x.Id && c.IsActive)); return await PageTasks(source,q.Page,q.PageSize,ct); }
    public async Task<PagedResult<AssignmentSummaryDto>> GetStaffListAsync(AssignmentListQuery q, Guid actor, string role, CancellationToken ct=default) { RequireStaff(role); return await List(db.CollectionAssignments.AsNoTracking(),q,ct); }
    public async Task<PagedResult<AssignmentSummaryDto>> GetMineAsync(AssignmentListQuery q, Guid actor, string role, CancellationToken ct=default) { if(role!=AppRoles.Driver) throw new ForbiddenException("Only Drivers can view their own assignments."); return await List(db.CollectionAssignments.AsNoTracking().Where(x=>x.DriverId==actor),q,ct); }
    public async Task<AssignmentDetailDto> GetDetailAsync(Guid id, Guid actor, string role, CancellationToken ct=default) { var a=await Base().SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new NotFoundException("Collection assignment was not found."); Authorize(a,actor,role); return Detail(a); }
    public async Task<RouteReadDto> GetRouteAsync(Guid id, Guid actor, string role, CancellationToken ct=default) { var a=await Base().SingleOrDefaultAsync(x=>x.Route!=null && x.Route.Id==id,ct)??throw new NotFoundException("Route was not found."); Authorize(a,actor,role); return Route(a.Route!); }
    private IQueryable<CollectionAssignment> Base()=>db.CollectionAssignments.AsNoTracking().Include(x=>x.Driver).ThenInclude(x=>x!.User).Include(x=>x.Vehicle).Include(x=>x.StatusHistory).Include(x=>x.Route).ThenInclude(x=>x!.Stops).ThenInclude(x=>x.CollectionTask!).ThenInclude(x=>x.WasteReport).Include(x=>x.Route).ThenInclude(x=>x!.Stops).ThenInclude(x=>x.CollectionTask!).ThenInclude(x=>x.WasteBin).Include(x=>x.Route).ThenInclude(x=>x!.Stops).ThenInclude(x=>x.StatusHistory);
    private async Task<PagedResult<AssignmentSummaryDto>> List(IQueryable<CollectionAssignment> source, AssignmentListQuery q, CancellationToken ct) { Validate(q.Page,q.PageSize); if(q.Status.HasValue) source=source.Where(x=>x.Status==q.Status); var total=await source.CountAsync(ct); var items=await source.Include(x=>x.Driver).ThenInclude(x=>x!.User).Include(x=>x.Vehicle).Include(x=>x.Route!).ThenInclude(x=>x.Stops).OrderByDescending(x=>x.AssignedAt).ThenBy(x=>x.Id).Skip((q.Page-1)*q.PageSize).Take(q.PageSize).ToListAsync(ct); return new(){Items=items.Select(Summary).ToList(),Page=q.Page,PageSize=q.PageSize,TotalCount=total}; }
    private static async Task<PagedResult<AssignmentTaskDto>> PageTasks(IQueryable<CollectionTask> s,int p,int n,CancellationToken ct){var total=await s.CountAsync(ct);var items=await s.OrderBy(x=>x.ScheduledAt).ThenBy(x=>x.TaskCode).Skip((p-1)*n).Take(n).ToListAsync(ct);return new(){Items=items.Select(Task).ToList(),Page=p,PageSize=n,TotalCount=total};}
    private static AssignmentSummaryDto Summary(CollectionAssignment a)=>new(){Id=a.Id,Status=a.Status,DriverId=a.DriverId,DriverName=a.Driver?.User?.FullName??string.Empty,VehicleId=a.VehicleId,VehicleRegistrationNumber=a.Vehicle?.RegistrationNumber??string.Empty,StopCount=a.Route?.Stops.Count??0,CompletedStopCount=a.Route?.Stops.Count(x=>x.Status==RouteStopStatus.Completed)??0,FailedStopCount=a.Route?.Stops.Count(x=>x.Status==RouteStopStatus.Failed)??0,AssignedAt=a.AssignedAt};
    private static AssignmentDetailDto Detail(CollectionAssignment a)=>new(){Id=a.Id,Status=a.Status,DriverId=a.DriverId,DriverName=a.Driver?.User?.FullName??string.Empty,VehicleId=a.VehicleId,VehicleRegistrationNumber=a.Vehicle?.RegistrationNumber??string.Empty,StopCount=a.Route?.Stops.Count??0,CompletedStopCount=a.Route?.Stops.Count(x=>x.Status==RouteStopStatus.Completed)??0,FailedStopCount=a.Route?.Stops.Count(x=>x.Status==RouteStopStatus.Failed)??0,AssignedAt=a.AssignedAt,Route=a.Route is null?null:Route(a.Route),History=a.StatusHistory.OrderBy(x=>x.ChangedAt).ThenBy(x=>x.Id).Select(x=>new AssignmentHistoryDto{Id=x.Id,FromStatus=x.FromStatus,ToStatus=x.ToStatus,ChangedByUserId=x.ChangedByUserId,ChangedAt=x.ChangedAt,Notes=x.Notes}).ToList()};
    private static RouteReadDto Route(Route r)=>new(){Id=r.Id,CollectionAssignmentId=r.CollectionAssignmentId,RoutingMethod=r.RoutingMethod,RouteGeometry=r.RouteGeometry,EstimatedDistanceMeters=r.EstimatedDistanceMeters,EstimatedDurationSeconds=r.EstimatedDurationSeconds,Stops=r.Stops.OrderBy(x=>x.Sequence).ThenBy(x=>x.Id).Select(x=>new RouteStopReadDto{Id=x.Id,Sequence=x.Sequence,Status=x.Status,CompletedAt=x.CompletedAt,FailedAt=x.FailedAt,FailureReason=x.FailureReason,Task=Task(x.CollectionTask!),History=x.StatusHistory.OrderBy(h=>h.ChangedAt).ThenBy(h=>h.Id).Select(h=>new RouteStopHistoryReadDto{Id=h.Id,FromStatus=h.FromStatus,ToStatus=h.ToStatus,ChangedByUserId=h.ChangedByUserId,ChangedAt=h.ChangedAt,Notes=h.Notes}).ToList()}).ToList()};
    private static AssignmentTaskDto Task(CollectionTask t)=>new(){Id=t.Id,TaskCode=t.TaskCode,TargetType=t.WasteReportId.HasValue?"Report":"Bin",WasteReportId=t.WasteReportId,WasteBinId=t.WasteBinId,CollectionReason=t.CollectionReason,Status=t.Status,ScheduledAt=t.ScheduledAt,AddressText=t.WasteReport?.AddressText??t.WasteBin?.AddressText,Latitude=t.WasteReport?.Latitude??t.WasteBin?.Latitude,Longitude=t.WasteReport?.Longitude??t.WasteBin?.Longitude};
    private static void Authorize(CollectionAssignment a,Guid actor,string role){if(role==AppRoles.WasteOfficer||role==AppRoles.MunicipalManager)return;if(role==AppRoles.Driver&&a.DriverId==actor)return;throw new ForbiddenException("You are not authorized to view this assignment.");} private static void RequireStaff(string role){if(role!=AppRoles.WasteOfficer&&role!=AppRoles.MunicipalManager)throw new ForbiddenException("Only municipal staff can view this resource.");} private static void Validate(int p,int n){if(p<1||n<1||n>50)throw new ValidationException("Invalid pagination.");}
}
