using SmartWaste.Domain.Collection.Enums;

namespace SmartWaste.Application.Collection.DTOs.Responses;

public class AssignmentSummaryDto { public Guid Id { get; set; } public long AssignmentNumber { get; set; } public string AssignmentReference => SmartWaste.Application.Fleet.AssignmentReference.FromNumber(AssignmentNumber); public CollectionAssignmentStatus Status { get; set; } public Guid DriverId { get; set; } public string DriverName { get; set; } = string.Empty; public Guid VehicleId { get; set; } public string VehicleRegistrationNumber { get; set; } = string.Empty; public int StopCount { get; set; } public int CompletedStopCount { get; set; } public int FailedStopCount { get; set; } public DateTime AssignedAt { get; set; } }
public sealed class AssignmentTaskDto { public Guid Id { get; set; } public string TaskCode { get; set; } = string.Empty; public string TargetType { get; set; } = string.Empty; public Guid? WasteReportId { get; set; } public Guid? WasteBinId { get; set; } public CollectionReason CollectionReason { get; set; } public CollectionTaskStatus Status { get; set; } public DateTime ScheduledAt { get; set; } public string? AddressText { get; set; } public double? Latitude { get; set; } public double? Longitude { get; set; } }
public sealed class RouteStopReadDto { public Guid Id { get; set; } public int Sequence { get; set; } public RouteStopStatus Status { get; set; } public DateTime? CompletedAt { get; set; } public DateTime? FailedAt { get; set; } public string? FailureReason { get; set; } public AssignmentTaskDto Task { get; set; } = new(); public IReadOnlyList<RouteStopHistoryReadDto> History { get; set; } = Array.Empty<RouteStopHistoryReadDto>(); }
public sealed class RouteStopHistoryReadDto { public Guid Id { get; set; } public RouteStopStatus? FromStatus { get; set; } public RouteStopStatus ToStatus { get; set; } public Guid? ChangedByUserId { get; set; } public DateTime ChangedAt { get; set; } public string? Notes { get; set; } }
public sealed class AssignmentHistoryDto { public Guid Id { get; set; } public CollectionAssignmentStatus? FromStatus { get; set; } public CollectionAssignmentStatus ToStatus { get; set; } public Guid? ChangedByUserId { get; set; } public DateTime ChangedAt { get; set; } public string? Notes { get; set; } }
public sealed class AssignmentDetailDto : AssignmentSummaryDto { public RouteReadDto? Route { get; set; } public IReadOnlyList<AssignmentHistoryDto> History { get; set; } = Array.Empty<AssignmentHistoryDto>(); }
public sealed class RouteReadDto { public Guid Id { get; set; } public Guid CollectionAssignmentId { get; set; } public RoutingMethod RoutingMethod { get; set; } public string? RouteGeometry { get; set; } public double? EstimatedDistanceMeters { get; set; } public double? EstimatedDurationSeconds { get; set; } public IReadOnlyList<RouteStopReadDto> Stops { get; set; } = Array.Empty<RouteStopReadDto>(); }
