"""SmartWaste LangGraph Orchestration Module.

Provides state management, transitions, error handling, and graph orchestration
for the SmartWaste agentic workflow.
"""

from app.orchestration.enums import (
    ApprovalPauseStage,
    GraphNodeId,
    OrchestrationPhase,
    OrchestrationStatus,
    ResumeDecision,
    SharedPlannerPolicy,
    WorkflowTriggerType,
)
from app.orchestration.errors import (
    COLLECTION_PLANNING_FAILED,
    FLEET_PLANNING_FAILED,
    INTERNAL_ORCHESTRATION_ERROR,
    INVALID_RESUME_CONTEXT,
    OPERATIONAL_VALIDATION_FAILED,
    PLANNER_VALIDATION_FAILED,
    PROVIDER_CONFIG_ERROR,
    PROVIDER_RATE_LIMIT,
    PROVIDER_UNAVAILABLE,
    STATE_INVARIANT_VIOLATION,
    WASTE_ANALYSIS_FAILED,
    OrchestrationError,
    create_orchestration_error,
)
from app.orchestration.graph import (
    COLLECTION_APPROVAL_PAUSE_REASON,
    DISPATCH_APPROVAL_PAUSE_REASON,
    build_collection_approval_phase_graph,
    build_report_verification_resume_graph,
    build_dispatch_planning_phase_graph,
    build_step9a_skeleton_graph,
    build_workflow_graph,
    deterministic_shared_planner_stub,
    failure_node,
    finish_node,
    dispatch_needs_revision_node,
    pause_for_collection_approval_node,
    pause_for_report_verification_node,
    pause_for_dispatch_approval_node,
    resume_after_collection_approval,
    resume_after_report_verification,
    run_collection_approval_phase,
    route_after_planner,
)
from app.orchestration.state import (
    FORBIDDEN_REASONING_KEYS,
    OrchestrationPauseResult,
    OrchestrationResultEnvelope,
    OrchestrationState,
    StateInvariantError,
    WorkflowResumeContext,
    validate_state_invariants,
)
from app.orchestration.transitions import (
    create_initial_state,
    mark_completed,
    mark_dispatch_needs_revision,
    mark_failed,
    mark_paused_for_approval,
    mark_planning_completed,
    mark_planning_started,
    mark_specialist_completed,
    mark_specialist_started,
)

__all__ = [
    # Enums
    "ApprovalPauseStage",
    "GraphNodeId",
    "OrchestrationPhase",
    "OrchestrationStatus",
    "ResumeDecision",
    "SharedPlannerPolicy",
    "WorkflowTriggerType",
    # Errors
    "OrchestrationError",
    "create_orchestration_error",
    "PLANNER_VALIDATION_FAILED",
    "WASTE_ANALYSIS_FAILED",
    "COLLECTION_PLANNING_FAILED",
    "FLEET_PLANNING_FAILED",
    "OPERATIONAL_VALIDATION_FAILED",
    "INVALID_RESUME_CONTEXT",
    "STATE_INVARIANT_VIOLATION",
    "PROVIDER_RATE_LIMIT",
    "PROVIDER_UNAVAILABLE",
    "PROVIDER_CONFIG_ERROR",
    "INTERNAL_ORCHESTRATION_ERROR",
    # State
    "OrchestrationState",
    "OrchestrationPauseResult",
    "WorkflowResumeContext",
    "OrchestrationResultEnvelope",
    "StateInvariantError",
    "FORBIDDEN_REASONING_KEYS",
    "validate_state_invariants",
    # Transitions
    "create_initial_state",
    "mark_planning_started",
    "mark_planning_completed",
    "mark_specialist_started",
    "mark_specialist_completed",
    "mark_paused_for_approval",
    "mark_failed",
    "mark_dispatch_needs_revision",
    "mark_completed",
    # Graph
    "deterministic_shared_planner_stub",
    "finish_node",
    "failure_node",
    "route_after_planner",
    "pause_for_collection_approval_node",
    "pause_for_report_verification_node",
    "pause_for_dispatch_approval_node",
    "dispatch_needs_revision_node",
    "COLLECTION_APPROVAL_PAUSE_REASON",
    "DISPATCH_APPROVAL_PAUSE_REASON",
    "build_step9a_skeleton_graph",
    "build_workflow_graph",
    "build_collection_approval_phase_graph",
    "build_report_verification_resume_graph",
    "run_collection_approval_phase",
    "resume_after_report_verification",
    "build_dispatch_planning_phase_graph",
    "resume_after_collection_approval",
]
