import axios from 'axios';
import React, { useCallback, useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Alert } from '../../../components/ui/Alert';
import { Button } from '../../../components/ui/Button';
import { Card } from '../../../components/ui/Card';
import { useCollectionNeeds } from '../hooks/useCollectionNeeds';
import { useCreateManualCollectionTask } from '../hooks/useCreateManualCollectionTask';
import { ManualCollectionTaskForm } from '../components/ManualCollectionTaskForm';
import type { CollectionNeedListParams, CollectionNeedReason, CollectionNeedTargetType } from '../types/collectionNeeds';
import type { CollectionNeedItemDto } from '../types/collectionNeeds';
import type { WasteType } from '../types/bins';
import type { CreateManualCollectionTaskRequest } from '../types/collectionTasks';
import { useAuthStore } from '../../../store/authStore';

type FilterState = Pick<CollectionNeedListParams, 'targetType' | 'collectionReason' | 'wasteType' | 'search'>;
const defaults: FilterState = { targetType: '', collectionReason: '', wasteType: '', search: '' };
const wasteTypes: WasteType[] = ['General', 'Organic', 'Recyclable', 'Hazardous', 'Bulky', 'Other'];
const reasons: CollectionNeedReason[] = ['VerifiedReport', 'FullOrBlockedBin', 'RoutineCollection'];
const urgencyClasses: Record<string, string> = { Urgent: 'bg-red-50 text-red-800 border-red-200', High: 'bg-amber-50 text-amber-800 border-amber-200', Medium: 'bg-blue-50 text-blue-800 border-blue-200', Low: 'bg-slate-100 text-slate-700 border-slate-200' };
const reasonLabels: Record<CollectionNeedReason, string> = { VerifiedReport: 'Verified report', FullOrBlockedBin: 'Full or blocked bin', RoutineCollection: 'Routine collection' };
const formatDate = (value: string) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false }).format(date); };

export const CollectionNeedsPage: React.FC = () => {
  const [filters, setFilters] = useState<FilterState>(defaults); const [page, setPage] = useState(1); const [search, setSearch] = useState('');
  const [selectedNeed, setSelectedNeed] = useState<CollectionNeedItemDto | null>(null); const [scheduleFeedback, setScheduleFeedback] = useState<string | null>(null); const [scheduleError, setScheduleError] = useState<string | null>(null);
  const navigate = useNavigate();
  const { user } = useAuthStore(); const isWasteOfficer = user?.role === 'WasteOfficer'; const scheduleTask = useCreateManualCollectionTask();
  useEffect(() => { const timer = setTimeout(() => { if (search !== filters.search) { setFilters((current) => ({ ...current, search })); setPage(1); } }, 350); return () => clearTimeout(timer); }, [filters.search, search]);
  const { needs, totalCount, totalPages, currentPage, pageSize, isLoading, isFetching, isError, errorMessage, refetch } = useCollectionNeeds({ ...filters, page, pageSize: 20 });
  const change = useCallback((partial: Partial<FilterState>) => { setFilters((current) => ({ ...current, ...partial })); setPage(1); }, []);
  const clear = () => { setFilters(defaults); setSearch(''); setPage(1); };
  const submitSchedule = (request: CreateManualCollectionTaskRequest) => { setScheduleFeedback(null); setScheduleError(null); scheduleTask.mutate(request, { onSuccess: (task) => { setSelectedNeed(null); setScheduleFeedback(`Collection task ${task.taskCode || task.id} was scheduled successfully.`); navigate(`/officer/tasks/${task.id}`); }, onError: (error) => { const response = axios.isAxiosError(error) ? error.response : undefined; const detail = response?.data?.detail || response?.data?.title; setScheduleError(response?.status === 409 ? detail || 'This target is no longer eligible or already has an active task. Refresh the queue and try another eligible need.' : detail || (error instanceof Error ? error.message : 'Unable to schedule the collection task.')); } }); };
  const filtered = Boolean(filters.search || filters.targetType || filters.collectionReason || filters.wasteType);
  return <div className="space-y-6"><header className="border-b border-slate-200/80 pb-5 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><div className="text-xs text-slate-400 font-medium mb-1">Operations / <span className="text-slate-600 font-semibold">Collection Needs</span></div><h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-slate-900">Collection Needs Queue</h1><p className="mt-1 text-sm text-slate-500">Derived, read-only operational candidates. The backend determines eligibility and active-task suppression.</p></div>{!isLoading && !isError && <span className="inline-flex px-3 py-1 rounded-full text-xs font-semibold bg-emerald-50 text-emerald-800 border border-emerald-200">{totalCount} {totalCount === 1 ? 'Need' : 'Total Needs'}</span>}</header>
    <Card className="p-4 sm:p-5"><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3"><label className="text-xs font-semibold text-slate-700">Search<input aria-label="Search collection needs" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Address or description..." className="mt-1 w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500" /></label><Select label="Target type" value={filters.targetType ?? ''} onChange={(value) => change({ targetType: value as CollectionNeedTargetType | '' })}><option value="">All targets</option><option value="Report">Waste reports</option><option value="Bin">Waste bins</option></Select><Select label="Collection reason" value={filters.collectionReason ?? ''} onChange={(value) => change({ collectionReason: value as CollectionNeedReason | '' })}><option value="">All reasons</option>{reasons.map((reason) => <option key={reason} value={reason}>{reasonLabels[reason]}</option>)}</Select><Select label="Waste type" value={filters.wasteType ?? ''} onChange={(value) => change({ wasteType: value as WasteType | '' })}><option value="">All waste types</option>{wasteTypes.map((type) => <option key={type} value={type}>{type}</option>)}</Select></div><div className="pt-3 mt-3 border-t border-slate-100 flex justify-between text-xs">{isFetching && !isLoading ? <span className="text-slate-400">Updating queue...</span> : <span />}{filtered && <Button variant="ghost" size="sm" onClick={clear} className="text-emerald-700">Clear filters</Button>}</div></Card>
    {isError && <Alert variant="error" className="flex items-center justify-between gap-4"><div><p className="font-semibold">Failed to load collection needs</p><p className="text-xs mt-1">{errorMessage}</p></div><Button variant="secondary" size="sm" onClick={() => refetch()}>Retry</Button></Alert>}
    {scheduleFeedback && <Alert variant="success" title="Collection task scheduled">{scheduleFeedback}</Alert>}
    {selectedNeed && <Card className="p-5 sm:p-6" data-testid="schedule-collection-card"><div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="text-lg font-bold text-slate-900">Schedule collection task</h2><p className="mt-1 text-sm text-slate-500">Review the selected target and submit the schedule for backend validation.</p></div><Button variant="ghost" size="sm" onClick={() => { setSelectedNeed(null); setScheduleError(null); }}>Close</Button></div>{scheduleError && <Alert variant="error" className="mb-5" title={scheduleError.includes('no longer eligible') ? 'Queue item may be outdated' : 'Unable to schedule task'}>{scheduleError}{scheduleError.includes('no longer eligible') && <Button variant="secondary" size="sm" className="mt-3" onClick={() => { setSelectedNeed(null); setScheduleError(null); refetch(); }}>Refresh queue</Button>}</Alert>}<ManualCollectionTaskForm need={selectedNeed} isSubmitting={scheduleTask.isPending} onSubmit={submitSchedule} onCancel={() => { setSelectedNeed(null); setScheduleError(null); }} /></Card>}
    <Card className="p-0 overflow-hidden"><NeedsTable needs={needs} isLoading={isLoading} filtered={filtered} onClear={clear} canSchedule={isWasteOfficer} onSchedule={(need) => { setScheduleFeedback(null); setScheduleError(null); setSelectedNeed(need); }} />{!isLoading && !isError && totalCount > 0 && <Pagination currentPage={currentPage} totalPages={totalPages} totalCount={totalCount} pageSize={pageSize} onPageChange={setPage} isLoading={isFetching} />}</Card>
  </div>;
};

const Select: React.FC<{ label: string; value: string; onChange: (value: string) => void; children: React.ReactNode }> = ({ label, value, onChange, children }) => <label className="text-xs font-semibold text-slate-700">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500">{children}</select></label>;

const NeedsTable: React.FC<{ needs: ReturnType<typeof useCollectionNeeds>['needs']; isLoading: boolean; filtered: boolean; onClear: () => void; canSchedule: boolean; onSchedule: (need: CollectionNeedItemDto) => void }> = ({ needs, isLoading, filtered, onClear, canSchedule, onSchedule }) => {
  if (isLoading) return <div className="p-6 space-y-3 animate-pulse" data-testid="collection-needs-loading">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="h-14 bg-slate-100 rounded" />)}</div>;
  if (!needs.length) return <div className="py-16 text-center" data-testid={filtered ? 'collection-needs-filtered-empty' : 'collection-needs-empty'}><p className="font-bold text-slate-800">{filtered ? 'No collection needs match the current filters.' : 'No collection needs at this time.'}</p><p className="mt-1 text-xs text-slate-500">{filtered ? 'Adjust the filters to review other derived needs.' : 'Eligible reports and bins will appear here when collection is required.'}</p>{filtered && <Button variant="secondary" size="sm" className="mt-4" onClick={onClear}>Clear filters</Button>}</div>;
  return <div className="overflow-x-auto"><table className="w-full min-w-[1080px] text-left text-xs"><thead><tr className="bg-slate-50 border-b border-slate-200 text-slate-500 uppercase tracking-wider"><th className="py-3.5 px-4">Target</th><th className="py-3.5 px-4">Location</th><th className="py-3.5 px-4">Reason</th><th className="py-3.5 px-4">Urgency</th><th className="py-3.5 px-4">Need details</th><th className="py-3.5 px-4">Triggered</th>{canSchedule && <th className="py-3.5 px-4 text-right">Action</th>}</tr></thead><tbody className="divide-y divide-slate-100">{needs.map((need) => { const detailPath = need.targetType === 'Bin' ? `/officer/bins/${need.id}` : `/officer/waste-reports/${need.id}`; const location = need.addressText?.trim() || `${need.latitude.toFixed(5)}, ${need.longitude.toFixed(5)}`; return <tr key={`${need.targetType}-${need.id}`} className="hover:bg-slate-50/70"><td className="py-3.5 px-4"><span className={`inline-flex px-2 py-0.5 rounded border text-[11px] font-semibold ${need.targetType === 'Bin' ? 'bg-emerald-50 text-emerald-800 border-emerald-200' : 'bg-blue-50 text-blue-800 border-blue-200'}`}>{need.targetType === 'Bin' ? 'Waste Bin' : 'Waste Report'}</span><Link to={detailPath} className="block mt-1.5 font-semibold text-emerald-700 hover:text-emerald-800" data-testid={`need-detail-${need.id}`}>{need.binDetails?.binCode || need.title}</Link></td><td className="py-3.5 px-4 max-w-60 text-slate-700">{location}</td><td className="py-3.5 px-4"><span className="text-slate-700">{reasonLabels[need.collectionReason]}</span><div className="mt-1 flex flex-wrap gap-1">{need.wasteTypes.map((type) => <span key={type} className="px-1.5 py-0.5 bg-slate-100 border border-slate-200 rounded text-slate-600">{type}</span>)}</div></td><td className="py-3.5 px-4"><span className={`inline-flex px-2 py-0.5 rounded border font-semibold ${urgencyClasses[need.urgency] || urgencyClasses.Low}`}>{need.urgency}</span></td><td className="py-3.5 px-4 text-slate-600">{need.targetType === 'Bin' && need.binDetails ? <><p>{need.binDetails.capacityLiters.toLocaleString()} L</p><p className="mt-1">{need.binDetails.latestFillLevelPercent === null ? 'Fill not recorded' : `Latest fill: ${need.binDetails.latestFillLevelPercent}%`}{need.binDetails.latestCondition ? ` · ${need.binDetails.latestCondition}` : ''}</p></> : <>{need.attachmentCount} {need.attachmentCount === 1 ? 'attachment' : 'attachments'}</>}</td><td className="py-3.5 px-4 text-slate-500 whitespace-nowrap">{formatDate(need.triggerDate)}</td>{canSchedule && <td className="py-3.5 px-4 text-right"><Button size="sm" onClick={() => onSchedule(need)} data-testid={`schedule-need-${need.id}`}>Schedule Collection</Button></td>}</tr>; })}</tbody></table></div>;
};

const Pagination: React.FC<{ currentPage: number; totalPages: number; totalCount: number; pageSize: number; onPageChange: (page: number) => void; isLoading: boolean }> = ({ currentPage, totalPages, totalCount, pageSize, onPageChange, isLoading }) => <div className="p-4 border-t border-slate-200 flex flex-col sm:flex-row justify-between gap-3 text-xs text-slate-500"><span>Showing {Math.min((currentPage - 1) * pageSize + 1, totalCount)} to {Math.min(currentPage * pageSize, totalCount)} of {totalCount} needs</span><div className="flex gap-2"><Button variant="secondary" size="sm" disabled={currentPage <= 1 || isLoading} onClick={() => onPageChange(currentPage - 1)}>Previous</Button><span className="px-2 py-1 font-semibold text-slate-700">Page {currentPage} of {Math.max(1, totalPages)}</span><Button variant="secondary" size="sm" disabled={currentPage >= totalPages || isLoading} onClick={() => onPageChange(currentPage + 1)}>Next</Button></div></div>;

export default CollectionNeedsPage;
